apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.monitoring_service_pod_role_oidc_access }}
  labels:
    service: monitoring-service
  name: monitoring-service-account
  namespace: {{ .Release.Namespace }}

