# Bind the role (to discover services) to the Spring Boot Admin service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-monitoring-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-monitoring-service
subjects:
- kind: ServiceAccount
  name: monitoring-service-account
  namespace: {{ .Release.Namespace }}

