apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring-service
  name: monitoring-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 7000
  selector:
    app: monitoring-service
