apiVersion: v1
kind: ConfigMap
metadata:
  name: products-service-config
  namespace: {{ .Release.Namespace }}
data:
  JAVA_XMS: {{ .Values.products_service_java_xms }}
  JAVA_XMX: {{ .Values.products_service_java_xmx }}
  PORT: '7000'
  MONITORING_URL: '{{ .Values.products_service_monitoring_url }}'
  DATABASE_HOST: '{{ .Values.products_service_database_host }}'
  DATABASE_PORT: '{{ .Values.products_service_database_port }}'
  DATABASE_SCHEMA: '{{ .Values.products_service_database_schema }}'
  DATABASE_USER: '{{ .Values.products_service_database_user }}'
  DATABASE_PASSWORD: '{{ .Values.products_service_database_password }}'
  REDIS_HOST: '{{ .Values.products_service_redis_host }}'
  REDIS_PORT: '{{ .Values.products_service_redis_port }}'
  OPENSEARCH_CONN: '{{ .Values.products_service_opensearch }}'
  ASSETS_BUCKET: '{{ .Values.products_service_assets_bucket }}'
  AWS_ACCESS_KEY_ID: 'test'
  AWS_SECRET_ACCESS_KEY: 'test'
  AWS_ENDPOINT: 'http://localhost:4566'
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_REGION: 'us-east-1'
  TRACING_URL: '{{ .Values.products_service_tracing_url }}'

