apiVersion: v1
kind: Service
metadata:
  labels:
    app: products-service
    type: spring-boot
  name: products-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-traffic
      port: 8000
      protocol: TCP
      targetPort: 7000
  selector:
    app: products-service
