apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: products-service-monitor
  labels:
    app: products-service-monitor
    release: prometheus-operator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: products-service
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
      interval: 5s
      scrapeTimeout: 5s
