apiVersion: v1
kind: ConfigMap
metadata:
  name: limiter-processor-service-config
  namespace: {{ .Release.Namespace }}
data:
  JAVA_XMS: {{ .Values.limiter_processor_service_java_xms }}
  JAVA_XMX: {{ .Values.limiter_processor_service_java_xmx }}
  PORT: '7000'
  MONITORING_URL: '{{ .Values.limiter_processor_service_monitoring_url }}'
  KAFKA_SERVERS: '{{ .Values.limiter_processor_service_kafka_servers }}'
  TRACING_URL: '{{ .Values.limiter_processor_service_tracing_url }}'
  REDIS_NODES: '{{ .Values.limiter_processor_service_redis_nodes }}'
  RATE_LIMIT: '{{ .Values.limiter_processor_service_rate_limit }}'

