apiVersion: v1
kind: ConfigMap
metadata:
  name: limiter-processor-service-config
  namespace: {{ .Release.Namespace }}
data:
  JAVA_XMS: {{ .Values.limiter_processor_service_java_xms }}
  JAVA_XMX: {{ .Values.limiter_processor_service_java_xmx }}
  PORT: '7000'
  MONITORING_URL: '{{ .Values.limiter_processor_service_monitoring_url }}'
  {{ if not (empty .Values.kind_gateway_id) }}
  REDIS_HOST: '{{ .Values.kind_gateway_id }}'
  {{ else}}
  REDIS_HOST: '{{ .Values.limiter_processor_service_redis_host }}'
  {{ end }}
  REDIS_PORT: '{{ .Values.limiter_processor_service_redis_port }}'
  KAFKA_SERVERS: '{{ .Values.limiter_processor_service_kafka_servers }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.limiter_processor_service_kafka_security_protocol }}'
  KAFKA_SASL_MECHANISM: '{{ .Values.limiter_processor_service_kafka_sasl_mechanism }}'
  {{ if not (empty .Values.kafka_password) }}
  KAFKA_SASL_JAAS_CONFIG: '{{ print "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"" .Values.kafka_user "\" password=\"" .Values.kafka_password "\";" }}'
  {{ end }}
  KAFKA_EXTRAS: '{{ .Values.limiter_processor_service_kafka_extras }}'
  TRACING_URL: '{{ .Values.limiter_processor_service_tracing_url }}'
  RATE_LIMIT: '{{ .Values.limiter_processor_service_rate_limit }}'

