apiVersion: v1
kind: Service
metadata:
  labels:
    app: limiter-processor-service
    type: spring-boot
  name: limiter-processor-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 7000
  selector:
    app: limiter-processor-service
