provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
  service:
    collector:
      otlp:
        grpc:
          name: otlp-grpc
          port: 4317
        http:
          name: otlp-http
          port: 4318
storage:
  type: badger
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
