apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-admin-bff
    type: spring-boot
  name: gateway-admin-bff
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 7000
  selector:
    app: gateway-admin-bff
