apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecomm-admin-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.gateway_ingress_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-admin-bff
                port:
                  name: http
