apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-service
  name: orders-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      serviceAccountName: orders-service-account
      containers:
        - name: orders-service
          image: {{ .Values.orders_service_image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
              name: http-port
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
          envFrom:
            - configMapRef:
                name: orders-service-config

