apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-by-api-request
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - curl -X POST http://orders-service:8000/api
          restartPolicy: OnFailure

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-by-run-app
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: run-job-clean-transactions
              image: {{ .Values.orders_service_image }}
              imagePullPolicy: IfNotPresent
              env:
                - name: runjob
                  value: "CLEAN_TRANSACTIONS"
          restartPolicy: Never
