apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-service-monitor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: orders-service
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: management-traffic
      path: "/actuator/prometheus"
      interval: 5s
      scrapeTimeout: 5s
