CREATE USER users_service WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD 'TO_BE_REPLACED';
CREATE USER products_service WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD 'TO_BE_REPLACED';
CREATE USER orders_service WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD 'TO_BE_REPLACED';
CREATE USER deployer WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD 'TO_BE_REPLACED';

GRANT deployer TO pgadmin;
CREATE DATABASE ecomm_users WITH OWNER deployer;
REVOKE deployer FROM pgadmin;

GRANT deployer TO pgadmin;
CREATE DATABASE ecomm_products WITH OWNER deployer;
REVOKE deployer FROM pgadmin;

GRANT deployer TO pgadmin;
CREATE DATABASE ecomm_orders WITH OWNER deployer;
REVOKE deployer FROM pgadmin;

