receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:14317"
      http:
        endpoint: "0.0.0.0:14318"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor
  attributes:
    actions:
      - key: job_name
        action: upsert
        from_attribute: service.name
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor
  metricstransform:
    transforms:
      - include: system.cpu.count
        action: update
        operations:
          - action: add_label
            new_label: version
            new_value: opentelemetry collector {{version}}

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [metricstransform]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [debug]
