apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
  namespace: {{ .Release.Namespace }}
data:
  JAVA_XMS: {{ .Values.users_service_java_xms }}
  JAVA_XMX: {{ .Values.users_service_java_xmx }}
  PORT: '7000'
  MANAGEMENT_PORT: '7001'
  MONITORING_URL: '{{ .Values.users_service_monitoring_url }}'
  {{ if not (empty .Values.kind_gateway_id) }}
  DATABASE_HOST: '{{ .Values.kind_gateway_id }}'
  {{ else }}
  DATABASE_HOST: '{{ .Values.users_service_database_host }}'
  {{ end }}
  DATABASE_PORT: '{{ .Values.users_service_database_port }}'
  DATABASE_SCHEMA: '{{ .Values.users_service_database_schema }}'
  DATABASE_USER: '{{ .Values.users_service_database_user }}'
  DATABASE_PASSWORD: '{{ .Values.users_service_database_password }}'
  {{ if not (empty .Values.kind_gateway_id) }}
  REDIS_HOST: '{{ .Values.kind_gateway_id }}'
  {{ else}}
  REDIS_HOST: '{{ .Values.users_service_redis_host }}'
  {{ end }}
  REDIS_PORT: '{{ .Values.users_service_redis_port }}'
  {{ if not (empty .Values.kind_gateway_id) }}
  OPENSEARCH_CONN: '-Dspring.jpa.properties.hibernate.search.backend.hosts={{ .Values.kind_gateway_id }}:9200'
  {{ else}}
  OPENSEARCH_CONN: '{{ .Values.users_service_opensearch }}'
  {{ end }}
  KAFKA_SERVERS: '{{ .Values.users_service_kafka_servers }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.users_service_kafka_security_protocol }}'
  KAFKA_SASL_MECHANISM: '{{ .Values.users_service_kafka_sasl_mechanism }}'
  {{ if not (empty .Values.kafka_password) }}
  KAFKA_SASL_JAAS_CONFIG: '{{ print "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"" .Values.kafka_user "\" password=\"" .Values.kafka_password "\";" }}'
  {{ end }}
  KAFKA_EXTRAS: '{{ .Values.users_service_kafka_extras }}'
  ASSETS_BUCKET: '{{ .Values.users_service_assets_bucket }}'
  AWS_ACCESS_KEY_ID: 'test'
  AWS_SECRET_ACCESS_KEY: 'test'
  AWS_ENDPOINT: 'http://localhost:4566'
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_REGION: 'us-east-1'
  TRACING_URL: '{{ .Values.users_service_tracing_url }}'
