apiVersion: v1
kind: Service
metadata:
  labels:
    app: users-service
    type: spring-boot
  name: users-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-traffic
      port: 8000
      protocol: TCP
      targetPort: 7000
    - name: management-traffic
      port: 8001
      protocol: TCP
      targetPort: 7001
  selector:
    app: users-service
