
products_pod_role_oidc_access:

products_service_image: sjexposecomm/products-service:latest
products_service_java_xms: 256m
products_service_java_xmx: 1g
products_service_monitoring_url: http://monitoring-service:9090
products_service_database_host:
products_service_database_port: 5432
products_service_database_schema: ecomm_products
products_service_database_user: products_service
products_service_database_password: "1234"
products_service_redis_host:
products_service_redis_port: 6379
products_service_assets_bucket: ecomm-assets-dev
products_service_opensearch:
products_service_tracing_url: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317
products_service_metrics_url: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317

# Special parameter to set by helm on command line
# kind_gateway_id:
