apiVersion: v1
kind: ConfigMap
metadata:
  name: limiter-kafka-mps-config
  namespace: {{ .Release.Namespace }}
data:
  JAVA_XMS: {{ .Values.limiter_kafka_mps_java_xms }}
  JAVA_XMX: {{ .Values.limiter_kafka_mps_java_xmx }}
  PORT: '7000'
  MANAGEMENT_PORT: '7001'
  MONITORING_URL: '{{ .Values.limiter_kafka_mps_monitoring_url }}'
  KAFKA_SERVERS: '{{ .Values.limiter_kafka_mps_kafka_servers }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.limiter_kafka_mps_kafka_security_protocol }}'
  KAFKA_SASL_MECHANISM: '{{ .Values.limiter_kafka_mps_kafka_sasl_mechanism }}'
  {{ if not (empty .Values.kafka_password) }}
  KAFKA_SASL_JAAS_CONFIG: '{{ print "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"" .Values.kafka_user "\" password=\"" .Values.kafka_password "\";" }}'
  {{ end }}
  KAFKA_EXTRAS: '{{ .Values.limiter_processor_service_kafka_extras }}'
  TRACING_URL: '{{ .Values.limiter_kafka_mps_tracing_url }}'
  PROCESSOR_SERVICE_BASEURI: '{{ .Values.limiter_kafka_mps_processor_baseuri }}'
  READER_QUEUE_SIZE: '{{ .Values.limiter_kafka_mps_reader_queue_size }}'
  WRITER_THREADS: '{{ .Values.limiter_kafka_mps_writer_threads }}'
  
