apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.limiter_kafka_mps_pod_role_oidc_access }}
  labels:
    service: limiter-kafka-mps
  name: limiter-kafka-mps-account
  namespace: {{ .Release.Namespace }}
