apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.admin_bff_pod_role_oidc_access }}
  labels:
    service: admin-bff
  name: admin-bff-account
  namespace: {{ .Release.Namespace }}
