apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-bff
  name: admin-bff
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: admin-bff
  template:
    metadata:
      labels:
        app: admin-bff
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: admin-bff-account
      containers:
        - name: admin-bff
          image: {{ .Values.admin_bff_image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
              name: http-port
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: "1024Mi"
            limits:
              cpu: 1000m
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
          envFrom:
            - configMapRef:
                name: admin-bff-config

