apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: admin-bff-monitor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: admin-bff
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics-traffic
      path: "/metrics"
      interval: 5s
      scrapeTimeout: 5s
